// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto1_BolsaEmpleo.Data;

#nullable disable

namespace Proyecto1_BolsaEmpleo.Migrations
{
    [DbContext(typeof(MyApiContext))]
    [Migration("20230426160458_migracion2")]
    partial class migracion2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CandidatoHabilidad", b =>
                {
                    b.Property<int>("candidatosId")
                        .HasColumnType("int");

                    b.Property<int>("habilidadesId")
                        .HasColumnType("int");

                    b.HasKey("candidatosId", "habilidadesId");

                    b.HasIndex("habilidadesId");

                    b.ToTable("CandidatoHabilidad", (string)null);
                });

            modelBuilder.Entity("EmpresaHabilidad", b =>
                {
                    b.Property<int>("empresasId")
                        .HasColumnType("int");

                    b.Property<int>("habilidadesId")
                        .HasColumnType("int");

                    b.HasKey("empresasId", "habilidadesId");

                    b.HasIndex("habilidadesId");

                    b.ToTable("EmpresaHabilidad", (string)null);
                });

            modelBuilder.Entity("Proyecto1_BolsaEmpleo.Models.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha_Nacimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Candidato");
                });

            modelBuilder.Entity("Proyecto1_BolsaEmpleo.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("Proyecto1_BolsaEmpleo.Models.Formacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Años_Estudio")
                        .HasColumnType("int");

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<string>("Fecha_Culminacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.ToTable("Formacion");
                });

            modelBuilder.Entity("Proyecto1_BolsaEmpleo.Models.Habilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Habilidad");
                });

            modelBuilder.Entity("Proyecto1_BolsaEmpleo.Models.Oferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Oferta");
                });

            modelBuilder.Entity("CandidatoHabilidad", b =>
                {
                    b.HasOne("Proyecto1_BolsaEmpleo.Models.Candidato", null)
                        .WithMany()
                        .HasForeignKey("candidatosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto1_BolsaEmpleo.Models.Habilidad", null)
                        .WithMany()
                        .HasForeignKey("habilidadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmpresaHabilidad", b =>
                {
                    b.HasOne("Proyecto1_BolsaEmpleo.Models.Empresa", null)
                        .WithMany()
                        .HasForeignKey("empresasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto1_BolsaEmpleo.Models.Habilidad", null)
                        .WithMany()
                        .HasForeignKey("habilidadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proyecto1_BolsaEmpleo.Models.Formacion", b =>
                {
                    b.HasOne("Proyecto1_BolsaEmpleo.Models.Candidato", "Candidato")
                        .WithMany("formaciones")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("Proyecto1_BolsaEmpleo.Models.Oferta", b =>
                {
                    b.HasOne("Proyecto1_BolsaEmpleo.Models.Empresa", "Empresa")
                        .WithMany("ofertas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Proyecto1_BolsaEmpleo.Models.Candidato", b =>
                {
                    b.Navigation("formaciones");
                });

            modelBuilder.Entity("Proyecto1_BolsaEmpleo.Models.Empresa", b =>
                {
                    b.Navigation("ofertas");
                });
#pragma warning restore 612, 618
        }
    }
}
